services:
    _defaults:
        autowire: true
        public: false

    LoremIpsum\RouteGeneratorBundle\Model\RouteGeneratorInterface: '@LoremIpsum\RouteGeneratorBundle\Utils\RouteGenerator'

    LoremIpsum\RouteGeneratorBundle\Utils\RouteGenerator:

    LoremIpsum\RouteGeneratorBundle\Twig\RouteGeneratorExtension:
        tags: ['twig.extension']
